* A
  - [[file:machin-learning/cs231n/neural-networks/neural-networks-part-1-setting-the-architecture.org::*Commonly used activation functions][activation functions]]
* C
  - [[file:machin-learning/cs231n/neural-networks/linear-classification-support-vector-machine-softmax.org][cs231n]]
  - [[file:machin-learning/cs231n/neural-networks/image-classifcation-data-driven-approach-k-nearest-neighbor-train-val-test-splits.org][cs231n]]
